version: "3.4"

services:
  xinfinsubnet1:
    build:
        context: .
        dockerfile: Dockerfile
        args:
          TIME: "${TIME}"
    volumes:
      - "./xdcchain-1:/work/xdcchain"
      - "./genesis.json:/work/genesis.json"
      - "./start.sh:/work/start.sh"
      - "./bootnodes.list:/work/bootnodes.list"
      - "./.pwd:/work/.pwd"
      - "/etc/localtime:/etc/localtime:ro"
    restart: "always"
    env_file: "./envs/${HOSTIP}-1"
    environment:
      - NODE_NUM=1
    ports:
      - "31303:30303"
      - "8645:8545"
      - "8655:8555"
    network_mode: host
