version: "3.7"

services:
  puppeth:
    image: xinfinorg/xdcsubnets:latest
    entrypoint: ["puppeth"]
    volumes:
      - "./puppeth:/root/.puppeth"
  bootnode:
    image: xinfinorg/xdcsubnets:latest
    restart: "always"
    env_file: ".env.bootnode"
    volumes:
      - "./bootnodes:/work/bootnodes"
    entrypoint: ["bash","/work/start-bootnode.sh"]
    command: ["-verbosity", "6", "-nodekey", "bootnode.key", "--addr", ":30301"]
    ports:
      - "30301:30301/tcp"
      - "30301:30301/udp"
  subnet:
    image: xinfinorg/xdcsubnets:latest
    volumes:
      - "./xdcchain:/work/xdcchain"
      - "./genesis.json:/work/genesis.json"
    restart: "always"
    env_file: ".env"
    ports:
      - "30303:30303"
      - "8545:8545"
      - "8555:8555"
  subnet2:
    image: xinfinorg/xdcsubnets:latest
    # entrypoint: "sleep infinity"
    volumes:
      - "./xdcchain2:/work/xdcchain"
      - "./genesis.json:/work/genesis.json"
    restart: "always"
    env_file: ".env2"
    ports:
      - "30304:30303"
      - "8546:8545"
      - "8556:8555"
  subnet3:
    image: xinfinorg/xdcsubnets:latest
    volumes:
      - "./xdcchain3:/work/xdcchain"
      - "./genesis.json:/work/genesis.json"
    restart: "always"
    env_file: ".env3"
    ports:
      - "30305:30303"
      - "8547:8545"
      - "8557:8555"
