version: "3.7"

services:
  puppeth:
    image: localbuild-subnet:latest
    entrypoint: ["puppeth"]
    volumes:
      - "./puppeth:/root/.puppeth"
  bootnode:
    image: localbuild-subnet:latest
    restart: "always"
    env_file: ".env.bootnode"
    volumes:
      - "./bootnodes:/work/bootnodes"
    entrypoint: ["bash","/work/start-bootnode.sh"]
    command: ["-verbosity", "6", "-nodekey", "bootnode.key", "--addr", ":30301"]
    ports:
      - "30301:30301/tcp"
      - "30301:30301/udp"
  subnet:
    image: localbuild-subnet:latest
    volumes:
      - "./xdcchain:/work/xdcchain"
      - "./genesis.json:/work/genesis.json"
    restart: "always"
    env_file: ".env"
    network_mode: "host" 
  subnet2:
    image: localbuild-subnet:latest
    volumes:
      - "./xdcchain2:/work/xdcchain"
      - "./genesis.json:/work/genesis.json"
    restart: "always"
    env_file: ".env.2"
    network_mode: "host" 
  subnet3:
    image: localbuild-subnet:latest
    volumes:
      - "./xdcchain3:/work/xdcchain"
      - "./genesis.json:/work/genesis.json"
    restart: "always"
    env_file: ".env.3"
    network_mode: "host" 