#!/bin/bash
cd "$(dirname "$0")"
if [ -z "$1" ]
  then
    echo "XDPoS.getV2Block()" > command.sh
  else
    if [ -n "$1" ] && [ "$1" -eq "$1" ] 2>/dev/null; then   #check if number
      echo "XDPoS.getV2Block($1)" > command.sh
    else
      echo $1 > command.sh
    fi
    
fi

docker exec -i subnet-subnet3-1 XDC attach /work/xdcchain/XDC.ipc < command.sh
